name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDevDebug
    - name: Upload debug APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: main-dev-debug.apk
        path: main/build/outputs/apk/dev/debug/main-dev-debug.apk
